### ISSUE TITLE
failed to build on ubuntu 14.04

### ISSUE THREAD

**Issue by dusteye** [limetext/lime#413]
I follow the build instruction  https://github.com/limetext/lime/wiki/Building-on-Ubuntu-14.04, but got stuck when I try this step
go get -u github.com/limetext/lime/frontend/termbox  
I got this:

<pre><code>
$ go get -u github.com/limetext/lime/frontend/termbox  
# github.com/limetext/lime/backend/commands
golang/src/github.com/limetext/lime/backend/commands/copycutpaste.go:31: cannot use rs (type *text.RegionSet) as type sort.Interface in function argument:
    *text.RegionSet does not implement sort.Interface (missing Less method)
golang/src/github.com/limetext/lime/backend/commands/copycutpaste.go:72: cannot use rs (type *text.RegionSet) as type sort.Interface in function argument:
    *text.RegionSet does not implement sort.Interface (missing Less method)
golang/src/github.com/limetext/lime/backend/commands/copycutpaste.go:90: cannot use rs (type *text.RegionSet) as type sort.Interface in function argument:
    *text.RegionSet does not implement sort.Interface (missing Less method)
</code></pre>

Is there anything wrong?
